#!/usr/bin/env python3
"""Build a merge worksheet for one chapter from the graded scribe notes.

This does not copy the winner. With only a few independent write-ups of
a lecture, the best of them still has holes -- and the grading pass already
produced the hole list, because `coverage_gaps` is a scored criterion. So the
worksheet starts from the strongest note and tells the editor, section by
section, what the others have that it does not.

It reads the *private* scribe repository and writes into this one:

    python scripts/promote.py --lecture 07 --scribe-repo ../ai618-scribe-2026f

Outputs:
    drafts/lec07-merge.md   the worksheet: ranking, gap union, errors to fix
    chapters/ch07.qmd       the top note, with the gap list carried in a
                            comment at the top -- the tool cannot tell where
                            in the prose a missing topic belongs

Neither output is finished work. The worksheet is a reading order for a human;
the chapter is a starting point that still needs the merge done by hand.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def load_grades(grades_repo: Path, lec: str) -> list[dict]:
    grade_dir = grades_repo / lec
    if not grade_dir.is_dir():
        return []
    records = [json.loads(p.read_text()) for p in sorted(grade_dir.glob("*.json"))]
    return sorted(records, key=lambda r: -r["aggregate"]["score"])


def note_sections(path: Path) -> list[str]:
    """Top-level and second-level headings, in order, as a coverage skeleton."""
    out = []
    in_fence = False
    for line in path.read_text().splitlines():
        if line.strip().startswith("```"):
            in_fence = not in_fence
        elif not in_fence and re.match(r"^#{1,3}\s+\S", line):
            out.append(line.strip())
    return out


def worksheet(lec: str, records: list[dict], scribe_repo: Path) -> str:
    lec_readme = scribe_repo / "lectures" / lec / "README.md"
    topics = lec_readme.read_text() if lec_readme.exists() else "(no lecture README found)"

    L = [f"# {lec} merge worksheet\n",
         "Generated by `scripts/promote.py`. This is a reading order, not a draft.\n",
         "## Candidates\n",
         "| rank | scribe | score | criterion medians | flags |",
         "|---|---|---|---|---|"]
    for i, r in enumerate(records, start=1):
        crit = r["aggregate"]["criteria"]
        medians = " / ".join(f"{crit[c]['median']:.0f}" for c in crit)
        flags = []
        if r["aggregate"].get("needs_human_attention"):
            flags.append("passes disagree >10")
        fluency = {f["level"] for f in r.get("english_fluency_flag", [])}
        if fluency & {"significant"}:
            flags.append("needs copy pass")
        L.append(f"| {i} | `{r['github']}` | {r['aggregate']['score']:.1f} | {medians} | "
                 f"{', '.join(flags) or '-'} |")
    L.append("\nCriterion order: coverage / correctness / exposition / figures / derivations.\n")

    L.append("## Gaps to fill in the base note\n")
    L.append(f"The base note is `{records[0]['github']}`. Every gap below was reported "
             "against it; the source column says which other note to lift the material "
             "from, where one of them covered it.\n")
    others = {r["github"]: {g["topic"].lower() for g in r["coverage_gaps"]} for r in records[1:]}
    L.append("| severity | topic | what is missing | covered by |")
    L.append("|---|---|---|---|")
    for gap in sorted(records[0]["coverage_gaps"],
                      key=lambda g: {"missing": 0, "thin": 1, "minor": 2}.get(g["severity"], 3)):
        covered = [name for name, gaps in others.items() if gap["topic"].lower() not in gaps]
        note = gap["note"].replace("\n", " ").replace("|", "\\|")
        L.append(f"| {gap['severity']} | {gap['topic']} | {note} | "
                 f"{', '.join(f'`{c}`' for c in covered) or '**nobody — write it**'} |")

    L.append("\n## Suspected errors across all candidates\n")
    L.append("Check every one of these against the lecture before publishing. The grader "
             "is unreliable on subtle mathematics in both directions: it invents errors "
             "and it misses them.\n")
    for r in records:
        errs = [e for e in r["suspected_errors"] if e.get("confidence") != "low"]
        if not errs:
            continue
        L.append(f"### `{r['github']}`\n")
        for e in errs:
            L.append(f"- **{e['location']}** ({e['confidence']} confidence, "
                     f"{e.get('raised_by_passes', 1)}/3 passes) — {e['claim']}  \n"
                     f"  Why: {e['why']}")
        L.append("")

    L.append("## Section skeletons, side by side\n")
    for r in records:
        path = scribe_repo / "lectures" / lec / "submissions" / f"{r['github']}.qmd"
        L.append(f"### `{r['github']}` ({r['aggregate']['score']:.1f})\n")
        if path.exists():
            L.extend(f"- {s}" for s in note_sections(path))
        else:
            L.append("- (file missing)")
        L.append("")

    L.append("## Lecture topic list (the coverage reference)\n")
    L.append(topics)
    return "\n".join(L) + "\n"


def copy_figures(lec: str, body: str, scribe_repo: Path) -> tuple[str, int, list[str]]:
    """Bring the base note's figures into this repository and repoint them.

    A submission refers to its figures as `../figures/name.png`, which resolves
    inside the scribe repository and nowhere else. Copying the prose alone
    leaves a chapter whose images 404 -- and Quarto does not fail on a missing
    image, so the build stays green and only the published page shows it. The
    files land in `chapters/figures/lecNN/` so that two scribes of different
    lectures cannot collide.
    """
    dest_dir = REPO / "chapters" / "figures" / lec
    src_dir = scribe_repo / "lectures" / lec / "figures"
    copied, missing = 0, []

    def repoint(m: re.Match) -> str:
        name = Path(m.group(2)).name
        src = src_dir / name
        if not src.exists():
            missing.append(name)
            return m.group(0)
        dest_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest_dir / name)
        nonlocal copied
        copied += 1
        return f"{m.group(1)}figures/{lec}/{name}"

    body = re.sub(r"(\]\()(\.\./figures/[^)\s]+)", repoint, body)
    return body, copied, missing


def seed_chapter(lec: str, records: list[dict], scribe_repo: Path) -> str:
    base = records[0]
    src = scribe_repo / "lectures" / lec / "submissions" / f"{base['github']}.qmd"
    text = src.read_text()

    # Replace the submission frontmatter with chapter frontmatter, crediting
    # everyone whose note fed the merge.
    if text.startswith("---"):
        lines = text.splitlines()
        for i in range(1, len(lines)):
            if lines[i].strip() in ("---", "..."):
                body = "\n".join(lines[i + 1:])
                break
        else:
            body = text
    else:
        body = text

    body, copied, missing = copy_figures(lec, body, scribe_repo)
    if copied:
        print(f"copied {copied} figure(s) into chapters/figures/{lec}/")
    for name in missing:
        print(f"  WARNING: {name} is referenced but not in the scribe repo; "
              "the published page will show a broken image")

    title = re.search(r'title:\s*"?([^"\n]+)"?', text)
    contributors = ", ".join(r["github"] for r in records)
    gaps = "\n".join(
        f"- **{g['severity'].upper()}: {g['topic']}** — {g['note']}"
        for g in base["coverage_gaps"]
    ) or "- (none reported)"

    name = title.group(1).strip() if title else f"Lecture {lec[3:]}"
    # Scribe notes are titled "Lecture 07 --- Flow Matching", which is how the
    # submission is identified. A book chapter is not identified that way: the
    # number is already in the chapter heading, and Part I would read "1
    # Lecture 01 --- ...". Keep only what follows the dash.
    name = re.sub(r"^Lecture\s*\d+\s*[-\u2013\u2014]+\s*", "", name)
    # lec00 is the instructor's preliminaries chapter, not one of the
    # lectures. It sits between the preface and Part I and carries
    # no number, so that chapter N keeps meaning lecture N for everything after
    # it. An unnumbered chapter is a heading with `.unnumbered`, not a YAML
    # title, which is how the preface and the references are written too.
    if lec == "lec00":
        head = f"# {name} {{.unnumbered}}\n"
    else:
        head = f'---\ntitle: "{name}"\n---\n'

    return head + f"""

<!--
DRAFT seeded by scripts/promote.py from the strongest {lec} scribe note.
Base note: {base['github']}. Merge sources: {contributors}.

This repository is public and this comment ships in the page source, so it
carries no scores and no per-note criticism. Both live in
drafts/{lec}-merge.md, which .gitignore keeps out of the repository.

Before this chapter is publishable:

1. Fill the gaps listed in drafts/{lec}-merge.md, which also says which of
   the other notes covered each one.
2. Resolve every suspected error in the worksheet against the lecture itself.
3. Reconcile notation with the neighbouring chapters.
4. Copy-edit. The scribe repository never penalised English fluency, so some
   base notes need a real pass here.
5. Replace this comment and the contributor list below with the final credit.
-->

::: {{.callout-important}}
## Draft
This chapter is a merge in progress and has not been edited or checked.
:::

{body}

---

*Scribe notes for this lecture: {contributors}.*
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lecture", required=True, help="lecture number, e.g. 07")
    ap.add_argument("--scribe-repo", default="../ai618-scribe-2026f",
                    help="path to the private scribe repository")
    ap.add_argument("--grades-repo", default="../ai618-grades-2026f",
                    help="path to the private grades repository -- grades are kept "
                         "out of the scribe repository, which students can read "
                         "and fork (default: ../ai618-grades-2026f)")
    ap.add_argument("--worksheet-only", action="store_true",
                    help="do not touch chapters/, only write the merge worksheet")
    ap.add_argument("--force", action="store_true",
                    help="overwrite a chapter that is no longer a stub")
    args = ap.parse_args()

    lec = f"lec{args.lecture.zfill(2)}"
    scribe_repo = Path(args.scribe_repo).expanduser().resolve()
    if not scribe_repo.is_dir():
        print(f"scribe repository not found: {scribe_repo}", file=sys.stderr)
        return 1

    grades_repo = Path(args.grades_repo).expanduser().resolve()
    records = load_grades(grades_repo, lec)
    if not records:
        print(f"No grades under {grades_repo}/{lec}. Grade the lecture first "
              "(scripts/grade_submissions.py --lecture "
              f"{args.lecture.zfill(2)}).", file=sys.stderr)
        return 1

    (REPO / "drafts").mkdir(exist_ok=True)
    ws = REPO / "drafts" / f"{lec}-merge.md"
    ws.write_text(worksheet(lec, records, scribe_repo))
    print(f"wrote {ws.relative_to(REPO)}  ({len(records)} candidate(s))")

    if args.worksheet_only:
        return 0

    chapter = REPO / "chapters" / f"ch{args.lecture.zfill(2)}.qmd"
    if chapter.exists() and "Not yet written" not in chapter.read_text() and not args.force:
        print(f"{chapter.relative_to(REPO)} has already been worked on; "
              "not overwriting (--force to override).")
        return 0
    chapter.write_text(seed_chapter(lec, records, scribe_repo))
    print(f"seeded {chapter.relative_to(REPO)} from `{records[0]['github']}` "
          f"({records[0]['aggregate']['score']:.1f}/100)")
    print("\nNeither file is finished. Read the worksheet, then merge by hand.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
